### PR TITLE
Quick fix

### PR DESCRIPTION
**Pull request by gibernas**

### CODE REVIEW

**Comment by gibernas** [comment]
@AleksandarPetrov Quick fix, i don't like too much the polling though

**Comment by AleksandarPetrov** [comment]
@gibernas doesn't this create an infinite call loop?

**Comment by gibernas** [comment]
That’s why one should go to sleep.

**Comment by AleksandarPetrov** [comment]
I am still confused. The `oneshot=False` option doesn't work?

**Comment by gibernas** [comment]
It’s the default

**Comment by AleksandarPetrov** [comment]
And why do we have updateParameters_() now?

**Comment by AleksandarPetrov** [comment]
And why do we have updateParameters_() now?

**Comment by gibernas** [comment]
@AleksandarPetrov  Did you fix the code on your side? Why not merged yet?

**Pull request closed without merging**
